data=importdata("MARGO_d18O_coretop.xls");
Latitudes=data.data(:,3);
Longitudes=data.data(:,4);
Age=data.data(:,9);
Gruberwhite=data.data(:,16);
Tsacculifer=data.data(:,36);
data2=importdata("MARGO_d18O_LateHolocene.xls");
Latitudes2=data2.data(:,3);
Longitudes2=data2.data(:,4);
Age2=data2.data(:,9);
Gruberwhite2=data2.data(:,16);
Tsacculifer2=data2.data(:,36);

Latitudes=[Latitudes;Latitudes2];
Longitudes=[Longitudes;Longitudes2];
Age=[Age;Age2];
Gruberwhite=[Gruberwhite;Gruberwhite2];
Tsacculifer=[Tsacculifer;Tsacculifer2];
save('MARGO_raw_data.mat','Age','Gruberwhite','Latitudes','Longitudes','Tsacculifer');